FROM postgres:14-alpine
ARG POSTGRES_USER
ENV POSTGRES_USER=${POSTGRES_USER}
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ARG POSTGRES_DB
ENV POSTGRES_DB=${POSTGRES_DB}
HEALTHCHECK --interval=5s --timeout=5s --retries=5 CMD pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
EXPOSE 5432
